@[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs icu-uc icu-i18n icu-io icu-lx icu-le || printf %s '-licuio -licui18n -liculx -licule -licuuc -licudata'`")]
lib LibICU
  alias WcharT = LibC::Int
  fun u_memcasecmp = u_memcasecmp_52(s1 : UChar*, s2 : UChar*, length : Int32T, options : Uint32T) : Int32T
  fun u_memchr32 = u_memchr32_52(s : UChar*, c : UChar32, count : Int32T) : UChar*
  fun u_memchr = u_memchr_52(s : UChar*, c : UChar, count : Int32T) : UChar*
  fun u_memcmp = u_memcmp_52(buf1 : UChar*, buf2 : UChar*, count : Int32T) : Int32T
  fun u_memcmp_code_point_order = u_memcmpCodePointOrder_52(s1 : UChar*, s2 : UChar*, count : Int32T) : Int32T
  fun u_memcpy = u_memcpy_52(dest : UChar*, src : UChar*, count : Int32T) : UChar*
  fun u_memmove = u_memmove_52(dest : UChar*, src : UChar*, count : Int32T) : UChar*
  fun u_memrchr32 = u_memrchr32_52(s : UChar*, c : UChar32, count : Int32T) : UChar*
  fun u_memrchr = u_memrchr_52(s : UChar*, c : UChar, count : Int32T) : UChar*
  fun u_memset = u_memset_52(dest : UChar*, c : UChar, count : Int32T) : UChar*
  fun u_str_case_compare = u_strCaseCompare_52(s1 : UChar*, length1 : Int32T, s2 : UChar*, length2 : Int32T, options : Uint32T, p_error_code : UErrorCode*) : Int32T
  fun u_str_compare = u_strCompare_52(s1 : UChar*, length1 : Int32T, s2 : UChar*, length2 : Int32T, code_point_order : UBool) : Int32T
  fun u_str_compare_iter = u_strCompareIter_52(iter1 : UCharIterator*, iter2 : UCharIterator*, code_point_order : UBool) : Int32T
  fun u_str_find_first = u_strFindFirst_52(s : UChar*, length : Int32T, substring : UChar*, sub_length : Int32T) : UChar*
  fun u_str_find_last = u_strFindLast_52(s : UChar*, length : Int32T, substring : UChar*, sub_length : Int32T) : UChar*
  fun u_str_fold_case = u_strFoldCase_52(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, options : Uint32T, p_error_code : UErrorCode*) : Int32T
  fun u_str_from_java_modified_ut_f8with_sub = u_strFromJavaModifiedUTF8WithSub_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f32 = u_strFromUTF32_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar32*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f32with_sub = u_strFromUTF32WithSub_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar32*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f8 = u_strFromUTF8_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f8lenient = u_strFromUTF8Lenient_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f8with_sub = u_strFromUTF8WithSub_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_wcs = u_strFromWCS_52(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : WcharT*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_has_more_char32than = u_strHasMoreChar32Than_52(s : UChar*, length : Int32T, number : Int32T) : UBool
  fun u_str_to_java_modified_ut_f8 = u_strToJavaModifiedUTF8_52(dest : LibC::Char*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : LibC::Char*
  fun u_str_to_lower = u_strToLower_52(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, locale : LibC::Char*, p_error_code : UErrorCode*) : Int32T
  fun u_str_to_title = u_strToTitle_52(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, title_iter : UBreakIterator, locale : LibC::Char*, p_error_code : UErrorCode*) : Int32T
  fun u_str_to_upper = u_strToUpper_52(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, locale : LibC::Char*, p_error_code : UErrorCode*) : Int32T
  fun u_str_to_ut_f32 = u_strToUTF32_52(dest : UChar32*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : UChar32*
  fun u_str_to_ut_f32with_sub = u_strToUTF32WithSub_52(dest : UChar32*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar32*
  fun u_str_to_ut_f8 = u_strToUTF8_52(dest : LibC::Char*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : LibC::Char*
  fun u_str_to_ut_f8with_sub = u_strToUTF8WithSub_52(dest : LibC::Char*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : LibC::Char*
  fun u_str_to_wcs = u_strToWCS_52(dest : WcharT*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : WcharT*
  fun u_strcasecmp = u_strcasecmp_52(s1 : UChar*, s2 : UChar*, options : Uint32T) : Int32T
  fun u_strcat = u_strcat_52(dst : UChar*, src : UChar*) : UChar*
  fun u_strchr32 = u_strchr32_52(s : UChar*, c : UChar32) : UChar*
  fun u_strchr = u_strchr_52(s : UChar*, c : UChar) : UChar*
  fun u_strcmp = u_strcmp_52(s1 : UChar*, s2 : UChar*) : Int32T
  fun u_strcmp_code_point_order = u_strcmpCodePointOrder_52(s1 : UChar*, s2 : UChar*) : Int32T
  fun u_strcpy = u_strcpy_52(dst : UChar*, src : UChar*) : UChar*
  fun u_strcspn = u_strcspn_52(string : UChar*, match_set : UChar*) : Int32T
  fun u_strlen = u_strlen_52(s : UChar*) : Int32T
  fun u_strncasecmp = u_strncasecmp_52(s1 : UChar*, s2 : UChar*, n : Int32T, options : Uint32T) : Int32T
  fun u_strncat = u_strncat_52(dst : UChar*, src : UChar*, n : Int32T) : UChar*
  fun u_strncmp = u_strncmp_52(ucs1 : UChar*, ucs2 : UChar*, n : Int32T) : Int32T
  fun u_strncmp_code_point_order = u_strncmpCodePointOrder_52(s1 : UChar*, s2 : UChar*, n : Int32T) : Int32T
  fun u_strncpy = u_strncpy_52(dst : UChar*, src : UChar*, n : Int32T) : UChar*
  fun u_strpbrk = u_strpbrk_52(string : UChar*, match_set : UChar*) : UChar*
  fun u_strrchr32 = u_strrchr32_52(s : UChar*, c : UChar32) : UChar*
  fun u_strrchr = u_strrchr_52(s : UChar*, c : UChar) : UChar*
  fun u_strrstr = u_strrstr_52(s : UChar*, substring : UChar*) : UChar*
  fun u_strspn = u_strspn_52(string : UChar*, match_set : UChar*) : Int32T
  fun u_strstr = u_strstr_52(s : UChar*, substring : UChar*) : UChar*
  fun u_strtok_r = u_strtok_r_52(src : UChar*, delim : UChar*, save_state : UChar**) : UChar*
end
