@[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs icu-uc icu-i18n icu-io 2> /dev/null|| printf %s '-licuio -licui18n -licuuc -licudata'`")]
lib LibICU
  {% begin %}
  alias WcharT = LibC::Int
  fun u_memcasecmp = u_memcasecmp{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*, length : Int32T, options : Uint32T) : Int32T
  fun u_memchr32 = u_memchr32{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar32, count : Int32T) : UChar*
  fun u_memchr = u_memchr{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar, count : Int32T) : UChar*
  fun u_memcmp = u_memcmp{{SYMS_SUFFIX.id}}(buf1 : UChar*, buf2 : UChar*, count : Int32T) : Int32T
  fun u_memcmp_code_point_order = u_memcmpCodePointOrder{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*, count : Int32T) : Int32T
  fun u_memcpy = u_memcpy{{SYMS_SUFFIX.id}}(dest : UChar*, src : UChar*, count : Int32T) : UChar*
  fun u_memmove = u_memmove{{SYMS_SUFFIX.id}}(dest : UChar*, src : UChar*, count : Int32T) : UChar*
  fun u_memrchr32 = u_memrchr32{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar32, count : Int32T) : UChar*
  fun u_memrchr = u_memrchr{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar, count : Int32T) : UChar*
  fun u_memset = u_memset{{SYMS_SUFFIX.id}}(dest : UChar*, c : UChar, count : Int32T) : UChar*
  fun u_str_case_compare = u_strCaseCompare{{SYMS_SUFFIX.id}}(s1 : UChar*, length1 : Int32T, s2 : UChar*, length2 : Int32T, options : Uint32T, p_error_code : UErrorCode*) : Int32T
  fun u_str_compare = u_strCompare{{SYMS_SUFFIX.id}}(s1 : UChar*, length1 : Int32T, s2 : UChar*, length2 : Int32T, code_point_order : UBool) : Int32T
  fun u_str_compare_iter = u_strCompareIter{{SYMS_SUFFIX.id}}(iter1 : UCharIterator*, iter2 : UCharIterator*, code_point_order : UBool) : Int32T
  fun u_str_find_first = u_strFindFirst{{SYMS_SUFFIX.id}}(s : UChar*, length : Int32T, substring : UChar*, sub_length : Int32T) : UChar*
  fun u_str_find_last = u_strFindLast{{SYMS_SUFFIX.id}}(s : UChar*, length : Int32T, substring : UChar*, sub_length : Int32T) : UChar*
  fun u_str_fold_case = u_strFoldCase{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, options : Uint32T, p_error_code : UErrorCode*) : Int32T
  fun u_str_from_java_modified_utf8_with_sub = u_strFromJavaModifiedUTF8WithSub{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f32 = u_strFromUTF32{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar32*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_utf32_with_sub = u_strFromUTF32WithSub{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar32*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_ut_f8 = u_strFromUTF8{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_utf8_lenient = u_strFromUTF8Lenient{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_utf8_with_sub = u_strFromUTF8WithSub{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : LibC::Char*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar*
  fun u_str_from_wcs = u_strFromWCS{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, p_dest_length : Int32T*, src : WcharT*, src_length : Int32T, p_error_code : UErrorCode*) : UChar*
  fun u_str_has_more_char32than = u_strHasMoreChar32Than{{SYMS_SUFFIX.id}}(s : UChar*, length : Int32T, number : Int32T) : UBool
  fun u_str_to_java_modified_ut_f8 = u_strToJavaModifiedUTF8{{SYMS_SUFFIX.id}}(dest : LibC::Char*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : LibC::Char*
  fun u_str_to_lower = u_strToLower{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, locale : LibC::Char*, p_error_code : UErrorCode*) : Int32T
  fun u_str_to_title = u_strToTitle{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, title_iter : UBreakIterator, locale : LibC::Char*, p_error_code : UErrorCode*) : Int32T
  fun u_str_to_upper = u_strToUpper{{SYMS_SUFFIX.id}}(dest : UChar*, dest_capacity : Int32T, src : UChar*, src_length : Int32T, locale : LibC::Char*, p_error_code : UErrorCode*) : Int32T
  fun u_str_to_ut_f32 = u_strToUTF32{{SYMS_SUFFIX.id}}(dest : UChar32*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : UChar32*
  fun u_str_to_utf32_with_sub = u_strToUTF32WithSub{{SYMS_SUFFIX.id}}(dest : UChar32*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : UChar32*
  fun u_str_to_ut_f8 = u_strToUTF8{{SYMS_SUFFIX.id}}(dest : LibC::Char*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : LibC::Char*
  fun u_str_to_utf8_with_sub = u_strToUTF8WithSub{{SYMS_SUFFIX.id}}(dest : LibC::Char*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, subchar : UChar32, p_num_substitutions : Int32T*, p_error_code : UErrorCode*) : LibC::Char*
  fun u_str_to_wcs = u_strToWCS{{SYMS_SUFFIX.id}}(dest : WcharT*, dest_capacity : Int32T, p_dest_length : Int32T*, src : UChar*, src_length : Int32T, p_error_code : UErrorCode*) : WcharT*
  fun u_strcasecmp = u_strcasecmp{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*, options : Uint32T) : Int32T
  fun u_strcat = u_strcat{{SYMS_SUFFIX.id}}(dst : UChar*, src : UChar*) : UChar*
  fun u_strchr32 = u_strchr32{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar32) : UChar*
  fun u_strchr = u_strchr{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar) : UChar*
  fun u_strcmp = u_strcmp{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*) : Int32T
  fun u_strcmp_code_point_order = u_strcmpCodePointOrder{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*) : Int32T
  fun u_strcpy = u_strcpy{{SYMS_SUFFIX.id}}(dst : UChar*, src : UChar*) : UChar*
  fun u_strcspn = u_strcspn{{SYMS_SUFFIX.id}}(string : UChar*, match_set : UChar*) : Int32T
  fun u_strlen = u_strlen{{SYMS_SUFFIX.id}}(s : UChar*) : Int32T
  fun u_strncasecmp = u_strncasecmp{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*, n : Int32T, options : Uint32T) : Int32T
  fun u_strncat = u_strncat{{SYMS_SUFFIX.id}}(dst : UChar*, src : UChar*, n : Int32T) : UChar*
  fun u_strncmp = u_strncmp{{SYMS_SUFFIX.id}}(ucs1 : UChar*, ucs2 : UChar*, n : Int32T) : Int32T
  fun u_strncmp_code_point_order = u_strncmpCodePointOrder{{SYMS_SUFFIX.id}}(s1 : UChar*, s2 : UChar*, n : Int32T) : Int32T
  fun u_strncpy = u_strncpy{{SYMS_SUFFIX.id}}(dst : UChar*, src : UChar*, n : Int32T) : UChar*
  fun u_strpbrk = u_strpbrk{{SYMS_SUFFIX.id}}(string : UChar*, match_set : UChar*) : UChar*
  fun u_strrchr32 = u_strrchr32{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar32) : UChar*
  fun u_strrchr = u_strrchr{{SYMS_SUFFIX.id}}(s : UChar*, c : UChar) : UChar*
  fun u_strrstr = u_strrstr{{SYMS_SUFFIX.id}}(s : UChar*, substring : UChar*) : UChar*
  fun u_strspn = u_strspn{{SYMS_SUFFIX.id}}(string : UChar*, match_set : UChar*) : Int32T
  fun u_strstr = u_strstr{{SYMS_SUFFIX.id}}(s : UChar*, substring : UChar*) : UChar*
  fun u_strtok_r = u_strtok_r{{SYMS_SUFFIX.id}}(src : UChar*, delim : UChar*, save_state : UChar**) : UChar*
  {% end %}
end
